herbal/urls.py
from django.contrib import admin
from django.urls import path, include
from myApp import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myApp.urls', namespace='index')),
   
    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

app_name = 'myAppurl'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('about/', views.about, name = 'about'),
    path('contact/', views.contact, name = 'contact'),
    path('herbal/', views.herbal, name = 'herbal'),
    path('testimonial/', views.testimonial, name = 'testimonial'),
    path('testimony/', views.testimony, name = 'testimony'),
    path('work/', views.work, name = 'work'),


   

]

myApp/models.py
from django.db import models
from django.utils.text import slugify


# Create your models here.
class product(models.Model):
    
    image = models.FileField(upload_to="img/%y")
    product_id = models.CharField(max_length=200)
    
    def __str__(self):
        return self.product_id


class testimonie(models.Model):
    
    image = models.FileField(upload_to="img/%y")
    name = models.CharField(max_length=200)
    date = models.CharField(max_length=200)
    testimony = models.CharField(max_length=200000)

    def __str__(self):
        return self.name

class contacts(models.Model):
    name = models.CharField(max_length=2000, null=False, blank=False)
    email = models.CharField(max_length=2000, null=False, blank=False)
    subject = models.CharField(max_length=2000, null=False, blank=False)
    body = models.CharField(max_length=200000, null=False, blank=False)
     
   
    def __str__(self):
        return self.name

myApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib import messages


from .models import testimonie
from .models import product
from .models import contacts



# Create your views here.

def home(request):

    pro = product.objects.all()


    return render(request, 'home.html', {'pro':pro})

def about(request):

    return render(request, 'about.html')

def herbal(request):

    return render(request, 'herbal.html')

def testimonial(request):

    fam = testimonie.objects.all()

    return render(request, 'testimonial.html', {'fam':fam})

def testimony(request):



    return render(request, 'testimony.html')

def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        body = request.POST['body']


        user_request = contacts(name=name, email=email, subject=subject, body=body)
        user_request.save()
        messages.success(request, f'Message Submitted... You will be contacted shortly through the email you provided')
        return redirect("index:contact")  

    return render(request, 'contact.html')

def work(request):

    return render(request, 'work.html')

myApp/templates/about.html
{% load static %} {% include 'topnav.html' %}
<link rel="stylesheet" href="{% static './about.css'%}" />

<section class="about-us">
  <div class="about">
    <div class="text">
      <h2>About Us</h2>

      <p>
        With several decades of experience and exposure, Doctor Emua has been
        helping and saving hundreds of lives from all over the world from
        different continents, religion, tribe or race. Unlike modern doctors,
        Doctor Emua focuses purely on using nature’s gifts in the production of
        Herbal Supplements which have been tested over the years to help to cure
        a wide range of illnesses, diseases and so forth. If a person looks
        deeply into the current norms, practices and ways with which modern
        science operate these days, one would be very careful to trust the whole
        system. Not to belittle the great effort of most doctors who have
        studied and worked hard in the system, but to state that all practices
        passed down to them as knowledge and research may be half truths or
        carefully calculated knowledge passed so as to drive certain agendas and
        policies for a select greddy and mischievous few. It is not very
        difficult to note that morden healthcare has neglected championing the
        need to promote healthy living and lifestyle, but rather are concerned
        with solving health issues. We also know that there are lots of health
        institutions that are covertly for profits and business. Infact these
        institutions are among the largest in the health sector and these
        include pharmacies and companies who provide health equipment
        (specifically for certain conditions). So not to sound so much like a
        conspiracy theorist, it should now be becoming common sense to know that
        there are persons who profit from our health issues or illness. And this
        is the reason why in the last 5 decades, there has been more than 150
        "incurable" illnesses that has been said to be discovered and these
        illnesses need a constant intake of certain drugs or a constant
        procedure to manage, and like you know, these things aren't cheap. I
        mean if your aren't paying for it, then your tax money is probably
        paying for it like in some areas. So people, don't you think the best
        thing a person should do is to learn to live a healthy life, eat well,
        and get natural cures for whatever ailment befalls the person ? It is
        now my job as a seasoned practitioner in herbal and holistic medicine to
        do the best I can to enlighten and educate persons on the importance of
        good living and plant based lifestyle and also to cure those suffering
        from lingering health issues. Contact us today for advice or to get a
        cure from the issue you have
      </p>
      <div class="data">
        <a href="{% url 'myAppurl:contact' %}" class="hire">Talk to Doctor Emua</a>
      </div>
    </div>
  </div>
</section>

<div>{% include 'mission.html' %}</div>

<div>{% include 'footer.html' %}</div>

myApp/templates/fontawesome.html
<link rel="stylesheet" href="../static/font-awesome-4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="../static/font-awesome-4.7.0/css/font-awesome.css">

myApp/templates/footer.html
{% load static %}
<link rel="stylesheet" href="{% static './footer.css'%}" />
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
/>

<footer>
  <div class="socialDiv">
    <div class="socialMedia">
      <a href="https://web.facebook.com/people/Dr-emua-herbal-home/100078712044063/"><i class="fa-brands fa-facebook-f"></i></a>
      <a href="https://api.whatsapp.com/message/SFIJKUKNKGLYC1?autoload=1&app_absent=0"><i class="fa-brands fa-whatsapp"></i></a>
      <a href="https://www.instagram.com/orion_herbal_home/?igshid=NTc4MTIwNjQ2YQ%3D%3D"><i class="fa-brands fa-instagram"></i></a>
    </div>
  </div>
  
  <div class="quicklinks">
    <a href="/">Home</a>
    <a href="{% url 'myAppurl:herbal' %}">Herbal Cure</a>
    <a href="{% url 'myAppurl:work' %}">How it Works</a>
    <a href="{% url 'myAppurl:contact' %}">Contact Us</a>

  </div>
  <hr style="color: gray"/>
  <p>Copyright @ doctoremuaherbalhome 2023</p>
</footer>

myApp/templates/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static './style.css'%}" />
    <link rel="stylesheet" href="{% static './testimony.css'%}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link
      rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <link rel="stylesheet" href="{% static
    './fontawesome-free-5.15.3-web/css/all.min.css'%} />
    <link
      rel="stylesheet"
      href="https://unpkg.com/swiper/swiper-bundle.min.css"
    />
  </head>
  <body>
   
    {% include 'topnav.html' %}

    <div class="background-image">
      <div class="background-content">
        <h1>
          DOCTOR EMUA <br />
          Herbal Home
        </h1>
        <p>
          welcome to the website of Doctor Emua, the number one herbal
          practitioner who is focused on improving the quality of life for
          families and communities around the world through advanced herbal and
          spiritual healthcare methods.
        </p>
        <a style="text-decoration: none;" href="{% url 'myAppurl:about' %}">Read more</a>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>

    <script>
      const swiper = new Swiper(".swiper", {
        autoHeight: true,
        loop: true,

        // If we need pagination
        pagination: {
          el: ".swiper-pagination",
        },

        // Navigation arrows
        navigation: {
          nextEl: ".swiper-button-next",
          prevEl: ".swiper-button-prev",
        },
      });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

myApp/templates/home.html
{% load static %}
{% include 'header.html' %}


<div class="about" id="about">
	<div class="main-about">
		<div class="inner-about">
			<div class="about-content">
				<h1>About Doctor Emua</h1>
				<p>With several decades of experience and exposure, Doctor Emua has been helping and saving hundreds of
					lives from all over the world from different continents, religion, tribe or race. Unlike modern
					doctors, Doctor. Emua focuses purely on using nature’s gifts in the production of Herbal Supplements
					which have been tested over the years to help to cure a wide range of illnesses, diseases and so
					forth.</p>
				<a style="text-decoration: none;" href="{% url 'myAppurl:about' %}">Read more</a>

			</div>

		</div>
		<div class="inner-about">
			<div class="inner-about-image">
				<img src="{% static './images/replacement.jpg'%}" alt="">
			</div>
		</div>
	</div>
</div>

<div class="boxContent">
	<div class="our-services">
	<div class="service-content">
		<div class="left-service-content">
			<h1>Why Doctor Emua</h1>
			<p>People have used herbs for thousands of years, relying on powdered supplements, teas, tinctures, and skin
				creams to help treat everything from skin rashes to mild depression. Herbal supplements, also known as
				botanicals, are made from the leaves, flowers, roots, and bark of plants. An herbalist is someone who
				uses plants for healing. These practitioners are not medical doctors, though some practitioners are also
				referred to as medical herbalist. Herbalists attempt to find the root cause of illness. Practitioners
				like Doctor Emua will choose herbs based on the symptoms or ailments a patient describes during
				consultation and generate a personalized prescription. Patients may use just one herbal treatment or a
				combination of herbal supplements.</p>
		</div>

	</div>

	<div>
		{% include 'mission.html' %}
	</div>
</div>


<div class="gallery">
	<h1>Our Treatment</h1>
	<div class="main-gallery">
		<p class="emuatreat">We offer you the best organic herbs and natural remedies to most diseases. We understand disease at a level beyond the superficial symptoms and strive to find a permanent resolution through God’s direction. We work with our patients and aim to bring about a State of Absolute health while using natural remedies and resources. With God’s Wisdom, direction and years of Study directed towards the natural healing properties of natural herbs, their amazing benefits to the human body we have developed a unique range of capsules, drops, bottled herbs and dried herbs. We have employed scientific and modern testing and extraction processes to ensure the preservation of these benefits of these extract and ensuring that they are made affordable and of good quality to anyone anywhere in the world. Some of Our Treatment available are listed Below:</p>
		<div class="inner-gallery">
			<img src="{% static './Images/auto.jpg'%}" alt="">
			<div class="abs">
				<p>Treatment for Autoimmune conditions</p>
				<div class="hovertext">
				<b>Yes you can be cured <br> All you have to do is ... </b>
				<a href="{% url 'myAppurl:contact' %}"><button>Contact Doctor Emua</button></a>
			</div>
			</div>
			
		</div>
	

		<div class="inner-gallery">
			<img src="{% static './images/detox.jpg'%}" alt="">
			<div class="abs">
				<p>Detox</p>
				<div class="hovertext">
				<b>Yes you can be cured <br> All you have to do is ... </b>
				<a href="{% url 'myAppurl:contact' %}"><button>Contact Doctor Emua</button></a>
				
			</div>
			</div>

			
		</div>
		<div class="inner-gallery">
			<img src="{% static './images/diabetes.jpg'%}" alt="">
			<div class="abs">
				<p>Cure for Diabetes</p>
				<div class="hovertext">
				<b>Yes you can be cured <br> All you have to do is ... </b>
				<a href="{% url 'myAppurl:contact' %}"><button>Contact Doctor Emua</button></a>
			
			</div>
			</div>
			
		</div>
		<div class="inner-gallery">
			<img src="{% static './images/epstein.jpg'%}" alt="">
			<div class="abs">
				<p>Cure for Epstein Bars Virus</p>
				<div class="hovertext">
				<b>Yes you can be cured <br> All you have to do is ... </b>
				<a href="{% url 'myAppurl:contact' %}"><button>Contact Doctor Emua</button></a>
			
			</div>
			</div>

			
		</div>

		<div class="inner-gallery">
			<img src="{% static './images/skin.jpg'%}" alt="">
			<div class="abs">
				<p>Cure for Skin Infection</p>
				<div class="hovertext">
				<b>Yes you can be cured <br> All you have to do is ... </b>
				<a href="{% url 'myAppurl:contact' %}"><button>Contact Doctor Emua</button></a>
				
			</div>
			</div>

			
		</div>
			<div class="inner-gallery">
			<img src="{% static './images/hepatitis b.jpg'%}" alt="">
			<div class="abs">
				<p>Cure for Hepatitis B</p>
				<div class="hovertext">
				<b>Yes you can be cured <br> All you have to do is ... </b>
				<a href="{% url 'myAppurl:contact' %}"><button>Contact Doctor Emua</button></a>
				
			</div>
			</div>

			
		</div>
			<div class="inner-gallery">
			<img src="{% static './images/hpv.jpg'%}" alt="">
			<div class="abs">
				<p>Cure for HPV</p>
				<div class="hovertext">
				<b>Yes you can be cured <br> All you have to do is ... </b>
				<a href="{% url 'myAppurl:contact' %}"><button>Contact Doctor Emua</button></a>
				
			</div>
			</div>

			
		</div>
			<div class="inner-gallery">
			<img src="{% static './images/herpes.jpg'%}" alt="">
			<div class="abs">
				<p> Cure for Herpes <br>...and so much more</p>
				<div class="hovertext">
				<b>So many other cures available, do no gamble with your life or the lives of your loved ones, speak with Doctor Emua</b>
				<a href="{% url 'myAppurl:herbal' %}"><button>See More</button></a>
				
			</div>
			</div>

			
		</div>




	</div>
</div>

 <div>
  {% include 'testimony.html' %}
 </div>  

 <div>
  {% include 'video.html' %}
 </div>  
</div>



{% include 'footer.html' %}

<script src="{% static './script.js'%}"></script>
</body>

</html>




<!-- provide an exceptional patient experience
<i class="fas fa-notes-medical"></i>
<i class="fas fa-hospital-user"></i>
<i class="fas fa-user-md"></i>
-->

myApp/templates/how.html
<section data-exad-particle-enable="false" class="elementor-section elementor-top-section elementor-element elementor-element-b27d055 elementor-section-boxed elementor-section-height-default elementor-section-height-default exad-parallax-effect-no exad-background-color-change-no exad-glass-effect-no exad-sticky-section-no" data-id="b27d055" data-element_type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
    <div class="elementor-background-overlay"></div>
    <div class="elementor-container elementor-column-gap-default">
    <div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-07d5347 exad-glass-effect-no exad-sticky-section-no" data-id="07d5347" data-element_type="column">
    <div class="elementor-widget-wrap elementor-element-populated">
    <div class="elementor-element elementor-element-fdeec4d exad-sticky-section-no exad-glass-effect-no elementor-widget elementor-widget-heading" data-id="fdeec4d" data-element_type="widget" data-widget_type="heading.default">
    <div class="elementor-widget-container">
    <h2 class="elementor-heading-title elementor-size-default">How it Works</h2> </div>
    </div>
    <div class="elementor-element elementor-element-dd79617 exad-sticky-section-no exad-glass-effect-no elementor-widget elementor-widget-spacer" data-id="dd79617" data-element_type="widget" data-widget_type="spacer.default">
    <div class="elementor-widget-container">
    <div class="elementor-spacer">
    <div class="elementor-spacer-inner"></div>
    </div>
    </div>
    </div>
    <section data-exad-particle-enable="false" class="elementor-section elementor-inner-section elementor-element elementor-element-6464eac elementor-section-boxed elementor-section-height-default elementor-section-height-default exad-parallax-effect-no exad-background-color-change-no exad-glass-effect-no exad-sticky-section-no" data-id="6464eac" data-element_type="section">
    <div class="elementor-container elementor-column-gap-default">
    <div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-563349f exad-glass-effect-yes exad-sticky-section-no" data-id="563349f" data-element_type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
    <div class="elementor-widget-wrap elementor-element-populated">
    <div class="elementor-element elementor-element-cfbb1da exad-sticky-section-no exad-glass-effect-no elementor-widget elementor-widget-exad-infobox" data-id="cfbb1da" data-element_type="widget" data-widget_type="exad-infobox.default">
    <div class="elementor-widget-container">
    <div class="exad-infobox">
    <div class="exad-infobox-item exad-infobox-align-center exad-infobox-icon-position-center exad-infobox-enable-box-yes simple-transition">
    <div class="exad-infobox-icon style_1">
    <i>1</i>
    </div>
    <div class="exad-infobox-content">
    <h3 class="exad-infobox-content-title">Contact Doctor Emua</h3>
    <div class="exad-infobox-content-description">Tell Us About your medical history and symptoms of your illness</div> </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    <div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-c9ead1f exad-glass-effect-yes exad-sticky-section-no" data-id="c9ead1f" data-element_type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
    <div class="elementor-widget-wrap elementor-element-populated">
    <div class="elementor-element elementor-element-2de2ed1 exad-sticky-section-no exad-glass-effect-no elementor-widget elementor-widget-exad-infobox" data-id="2de2ed1" data-element_type="widget" data-widget_type="exad-infobox.default">
    <div class="elementor-widget-container">
    <div class="exad-infobox">
    <div class="exad-infobox-item exad-infobox-align-center exad-infobox-icon-position-center exad-infobox-enable-box-yes simple-transition">
    <div class="exad-infobox-icon style_1">
    <i>2</i>
    </div>
    <div class="exad-infobox-content">
    <h3 class="exad-infobox-content-title">personalised care</h3>
    <div class="exad-infobox-content-description">We'll then provide you with a tailored treatment plan
    </div> </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    <div class="elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-701ad96 exad-glass-effect-yes exad-sticky-section-no" data-id="701ad96" data-element_type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
    <div class="elementor-widget-wrap elementor-element-populated">
    <div class="elementor-element elementor-element-e2b74c3 exad-sticky-section-no exad-glass-effect-no elementor-widget elementor-widget-exad-infobox" data-id="e2b74c3" data-element_type="widget" data-widget_type="exad-infobox.default">
    <div class="elementor-widget-container">
    <div class="exad-infobox">
    <div class="exad-infobox-item exad-infobox-align-center exad-infobox-icon-position-center exad-infobox-enable-box-yes simple-transition">
    <div class="exad-infobox-icon style_1">
    <i>3</i>
    </div>
    <div class="exad-infobox-content">
    <h3 class="exad-infobox-content-title">Get next day delivery</h3>
    <div class="exad-infobox-content-description">Receive genuine herbal medications shipped discreetly to your door
    </div> </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </section>
    <div class="elementor-element elementor-element-de7cbd1 exad-sticky-section-no exad-glass-effect-no elementor-widget elementor-widget-spacer" data-id="de7cbd1" data-element_type="widget" data-widget_type="spacer.default">
    <div class="elementor-widget-container">
    <div class="elementor-spacer">
    <div class="elementor-spacer-inner"></div>
    </div>
    </div>
    </div>
    <div class="exad-link-anything-wrapper elementor-element elementor-element-8fbb88d elementor-icon-list--layout-inline elementor-align-center elementor-list-item-link-full_width exad-sticky-section-no exad-glass-effect-no elementor-widget elementor-widget-icon-list" data-exad-element-link="{&quot;url&quot;:&quot;&quot;,&quot;is_external&quot;:&quot;&quot;,&quot;nofollow&quot;:&quot;&quot;,&quot;custom_attributes&quot;:&quot;&quot;}" style="cursor: pointer" data-id="8fbb88d" data-element_type="widget" data-widget_type="icon-list.default">
    <div class="elementor-widget-container">
    <ul class="elementor-icon-list-items elementor-inline-items">
    <li class="elementor-icon-list-item elementor-inline-item">
    <span class="elementor-icon-list-icon">
        <i class="fa fa-long-arrow-right" aria-hidden="true"></i> </span>
    <span class="elementor-icon-list-text"> <a style="color: #FFFFFF;" href="{% url 'myAppurl:herbal' %}"> view process in full</a> </span>
    </li>
    </ul>
    </div>
    </div>
    </div>
    </div>
    </div>
    </section>

myApp/templates/testimony.html
{% load static %}
<link rel="stylesheet" href="{% static './testimony.css'%}" />

<div class="testimonial">
  <h4>Testimony</h4>
  <h5>See what people are saying about Doctor Emua</h5>
  <div class="Boxcard">
    <div class="innerCard">
      <img src="../static/Images/random4.jpg" alt="" />
      <div class="testiBody">
        <p class="name">Veronica</p>
        <p class="bodyText">
          I’m Veronica from Canada, i was diagnosed with Hepatitis B 4 years ago,
          i lived in pain with the knowledge that i wasn’t going to ever be well
          okay, i contacted so many herbal doctors about herbs to cure me and
          ended up spending some amount of money but i never got better i was
          determined to get my lifestyle back and ... <a href="{% url 'myAppurl:testimonial' %}"> read more </a>
        </p>
      </div>
      <div class="cured"><p>Cured from Hepatitis B</p></div>
    </div>
    <div class="innerCard">
      <img src="../static/Images/random1.jpg" alt="" />
      <div class="testiBody">
        <p class="name">Thomas Herman</p>
        <p class="bodyText">
          Hello everyone, Thomas Herman from Florida, USA and i’m very happy
          today to share this amazing testimony as Doctor Emua the herbal doctor
          was able to cure me from my Herpes Virus with his herbal medicine.I
          was been a diagnosed of HSV2 for a period of 4 years and have tried
          different methods of...<a href="{% url 'myAppurl:testimonial' %}"> read more </a>
        </p>
      </div>
      <div class="cured"><p>Cured from Herpes Virus</p></div>
    </div>
    <div class="innerCard">
      <img src="../static/Images/stephanie.jpg" alt="" />
      <div class="testiBody">
        <p class="name">Stephanie</p>
        <p class="bodyText">
          Hello, I want to write a little review about the good work of Doctor
          Emua, who cured me from HSV 1&2 in just 2 weeks with his herbal
          medicine, I never believe I can be cured again and have a good life
          like others, I always regretted the day I got diagnose with this
          virus, I become lost of hope when my doctor told me...
          <a href="{% url 'myAppurl:testimonial' %}"> read more </a>
        </p>
      </div>
      <div class="cured"><p>Cured from HSV 1&2</p></div>
    </div>
    <div class="innerCard">
      <img src="../static/Images/shane.jpg" alt="" />
      <div class="testiBody">
        <p class="name">Shane Jenkins</p>
        <p class="bodyText">
          My daughter purchased your product for me. When I saw the title, I was
          very sceptical. I was told by my doctor that my condition (knee OA)
          was age-related, irreversible and I needed joint replacement surgery.
          Nevertheless, I used your product and started to follow your
          guidelines because I had nothing to lose... <a href="{% url 'myAppurl:testimonial' %}"> read more </a>
        </p>
      </div>
      <div class="cured"><p>Cured from Knee OA</p></div>
    </div>
  </div>
</div>

myApp/templates/topnav.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <style>
      body {
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
      }

      .topBox {
        display: flex;
        justify-content: space-between;
      }

      .topnav {
        overflow: hidden;
        background-color: #000;
      }

      .topnav a {
        float: left;
        display: block;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
      }

      .topnav a:hover {
        background-color: #ddd;
        color: black;
      }

      .topnav a.active {
        /* background-color: #04aa6d; */
        color: white;
      }

      .topnav .icon {
        display: none;
      }

      @media screen and (max-width: 600px) {
        .topnav a:not(:first-child) {
          display: none;
        }
        .topnav a.icon {
          float: right;
          display: block;
        }
      }

      @media screen and (max-width: 600px) {
        .topnav.responsive {
          position: relative;
        }
        .topnav.responsive .icon {
          position: absolute;
          right: 0;
          top: 0;
        }
        .topnav.responsive a {
          float: none;
          display: block;
          text-align: left;
        }
      }
    </style>
  </head>
  <body>
    <div class="topnav" id="myTopnav">
      <a href="/" class="active">
        <img
          src="../static/Images/logo.png"
          style="width: 90px; height: 30px"
          alt=""
        />
      </a>
      <a href="{% url 'myAppurl:about' %}">About Us</a>
      <a href="{% url 'myAppurl:testimonial' %}">Testimonial</a>
	        <a href="{% url 'myAppurl:contact' %}">Contact Us</a>
      <a href="{% url 'myAppurl:herbal' %}">Herbal Cure</a>
      <a href="javascript:void(0);" class="icon" onclick="myFunction()">
        <i class="fa fa-bars"></i>
      </a>
    </div>

    <script>
      function myFunction() {
        var x = document.getElementById("myTopnav");
        if (x.className === "topnav") {
          x.className += " responsive";
        } else {
          x.className = "topnav";
        }
      }
    </script>
  </body>
</html>

myApp/templates/video.html
{% load static %}
<link rel="stylesheet" href="{% static './video.css'%}" />

<div class="review">
    <h2>Product & Review</h2>
    <div class="videoCard">
        <div class="video">
            <video src="{% static './video/girl3.mp4'%}" style="width: 100%; height: 100%;" controls ></video>
        </div>
          <div class="video">
            <video src="{% static './video/vid1.mp4'%}" style="width: 100%; height: 100%;" controls ></video>
        </div>
          <div class="video">
            <video src="{% static './video/vid4.mp4'%}" style="width: 100%; height: 100%;" controls ></video>
        </div>
          <div class="video">
            <video src="{% static './video/vid2.mp4'%}" style="width: 100%; height: 100%;" controls></video>
        </div>
    </div>
</div>